[[libosrmc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c6a1e9ffd41d4a71910362b68db60272361b59a6"
os = "windows"

    [[libosrmc.download]]
    sha256 = "a2dea74b663e4a28c6290d91b985d85787ef486e3c64ca73c2c3bc7998a6a163"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.i686-w64-mingw32-cxx11.tar.gz"
[[libosrmc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7a929a6d66877a9abcf12869782f27cf2dd69a98"
os = "windows"

    [[libosrmc.download]]
    sha256 = "3b93e98527b9ac226fbdcf50100f2e0484d743da410843bd47fa4675bb9f70f0"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
[[libosrmc]]
arch = "aarch64"
git-tree-sha1 = "da8859c2f155139aba1c52479985922bf14f3a42"
os = "macos"

    [[libosrmc.download]]
    sha256 = "0fd4f1fdb7d0ad3297656d2de43193f6194dfde4146aa9bf0c9107d9cd6fee7d"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.aarch64-apple-darwin.tar.gz"
[[libosrmc]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bbde12920ca98fcf83a0b9ea0e7635bf974d660a"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "e27a61312cf0c1e7a93ac0230726711ffa2b00b27fd0c9266fad73ac3a71c188"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[libosrmc]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "030b8ab17018558a9d99e02de55d046407397702"
libc = "musl"
os = "linux"

    [[libosrmc.download]]
    sha256 = "f4143b03a31665aef5b99826277d010083b205e6f95fdf06d911986684108dca"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.aarch64-linux-musl-cxx11.tar.gz"
[[libosrmc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c5f1f757466a1d02232dc80d5e725f4c5b11efd4"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "981ee3079aa4c13469c18aec9d230a380bc09fad3d5d11ad77216f0690d9f6aa"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[libosrmc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "38750219382075979e6c38f38a65961acc0798ba"
libc = "musl"
os = "linux"

    [[libosrmc.download]]
    sha256 = "7f6adf93b2453df8d384747c19e2f1b8c9885e7b67bab34c015993d0e0ce3dc0"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[libosrmc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "26a5a62afc34dc4fb85500e81c685e1d24307fdf"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "df39b7ef68e0a58508f09cf258b7f2fa9493305e4ad97e4df43494fab7280bc8"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libosrmc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "78123fca9884b08cb9e6db529415ff8db3492fce"
libc = "musl"
os = "linux"

    [[libosrmc.download]]
    sha256 = "aaf872677abb82eb0a588c3c043cfe2b50bbc7d2ae50d3765a8160ff949dfeb9"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libosrmc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6e3836882f8109cdc6c0025573a12907fada7b95"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "2d40dbe1e0cedff25f1f19e5009b555c636dd9616843097350e879077d38dec5"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.i686-linux-gnu-cxx11.tar.gz"
[[libosrmc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f208dc295d6e53f06b89694d0556b0724ab9d0a6"
libc = "musl"
os = "linux"

    [[libosrmc.download]]
    sha256 = "e307f463ad113c2eaa2cda279af5844ad9f074edfc965823d8f85ebdd607cedb"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.i686-linux-musl-cxx11.tar.gz"
[[libosrmc]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a6696d5f48ec060a8d2069d7c79bc249117389bf"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "9dbe045bbe87c96c2b02eb7c242917d2922b2583d14278ef7f6947d7a8b648d9"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libosrmc]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "afbb065966ebb910fab22ae7786f38dca48c9a2b"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "006d61b02b749b3a08feb86d90dd8d61899efa738ec9b843e745054ccd96fb81"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.riscv64-linux-gnu-cxx11.tar.gz"
[[libosrmc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5ae245ce114912a8a87215b92d9f4b016212aed2"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "d3fb3b459e6575c34bf6ec20bde0ab9174eaefeedf8a7fe2fd86fa56c276061e"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[libosrmc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "afc3ca30a2ffb013990fae1c8e6b841c3436430d"
libc = "musl"
os = "linux"

    [[libosrmc.download]]
    sha256 = "47bb80f2648a168446cfbcedc1c6e19d401ee05a5d3f39effa387b57405e7630"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.x86_64-linux-musl-cxx11.tar.gz"
