[[libosrmc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c6a1e9ffd41d4a71910362b68db60272361b59a6"
os = "windows"

    [[libosrmc.download]]
    sha256 = "a2dea74b663e4a28c6290d91b985d85787ef486e3c64ca73c2c3bc7998a6a163"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.i686-w64-mingw32-cxx11.tar.gz"
[[libosrmc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7a929a6d66877a9abcf12869782f27cf2dd69a98"
os = "windows"

    [[libosrmc.download]]
    sha256 = "3b93e98527b9ac226fbdcf50100f2e0484d743da410843bd47fa4675bb9f70f0"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
[[libosrmc]]
arch = "aarch64"
git-tree-sha1 = "6dcae76fa9a071722f80ec813728cb81e623203e"
os = "macos"

    [[libosrmc.download]]
    sha256 = "533f930eb50041e9fff99323d7379eacff12201b3d9b2c9177552462e494d8ca"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.aarch64-apple-darwin.tar.gz"
[[libosrmc]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f71dbaec0e3c26cfce9d448724c85bd66804c179"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "37eff81c4075f3b7be63991458c2954da0480cea1341e2046f0007da516bf55d"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[libosrmc]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c720d0bc21a637229dbc2f4e64bd38a7ec72367c"
libc = "musl"
os = "linux"

    [[libosrmc.download]]
    sha256 = "71e060a5a85467cd553aa4c08bbe7b0a6f5b587ca269a31ef7fe1b06f0196d3e"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.aarch64-linux-musl-cxx11.tar.gz"
[[libosrmc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1efb7feb21cbb56666ca7eb61f881e603b0656f5"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "f60c73b968b204c0425f090382ed32c54bcb11158994db006e180ada1a8483fb"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[libosrmc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1dd3e659d85e18bf0068c1b6044a4933dfbaf5c9"
libc = "musl"
os = "linux"

    [[libosrmc.download]]
    sha256 = "1b75c912cde52b2ef6ef80c8ff4936c9fa80b02d8e94f42a2dcfcb8f57998cb4"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[libosrmc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4c6bf125111cfe3b08d089a4cbe82e44a9acbe86"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "ede7701737898a9c1e9f8ec02bf6cc6725a71e9301dff6a6172be2ef332de81a"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libosrmc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "885021e09bfd03c2aa4b13fe2e34f113e06e017d"
libc = "musl"
os = "linux"

    [[libosrmc.download]]
    sha256 = "a5d28b8826f17a79838eb60f8b1caccaa5b718456a080bc3e2a947bf848bbb53"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libosrmc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e06ffdabdd5bf01e0f7a7091b22c74d612d7ebf5"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "b38a03569a0947f6d4f7f5579111f2f6cb4b2df8e6bf338d2b9f6ca147545085"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.i686-linux-gnu-cxx11.tar.gz"
[[libosrmc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0bdc40fa3698abda6794c0e3ca13daed487462c7"
libc = "musl"
os = "linux"

    [[libosrmc.download]]
    sha256 = "88d7be13b6f5dc728385566c69a8714cd29fc5bc22301c7456295866e9f55b5a"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.i686-linux-musl-cxx11.tar.gz"
[[libosrmc]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "72ed390721ca71999608c9137958bd510493d4aa"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "59fb52c234edcba34d85d10c1873cb939ae12afd41afb0293132688867c6cfb2"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libosrmc]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9a61af6433d2db0de2c7a5092847d373edd170c3"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "484a04000dfe254a8f9d351d4ec2e45bcb49806a12904bf9708b4580c3f005b8"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.riscv64-linux-gnu-cxx11.tar.gz"
[[libosrmc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b82b7f6bce44e1092625eb599d14bdb0be515689"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "f040575513a973e29d056b7e3b9675925d543dbfe8008de86df1a2207116d46d"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[libosrmc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "afee76915d5bce0c539188a1d0d8501d4698103a"
libc = "musl"
os = "linux"

    [[libosrmc.download]]
    sha256 = "84fef209cbfaa91ccf9aa90e3800569e8b77cc5cbd23ec7046f3a0d2e6e0a1bb"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.x86_64-linux-musl-cxx11.tar.gz"
