[[libosrmc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c6a1e9ffd41d4a71910362b68db60272361b59a6"
os = "windows"

    [[libosrmc.download]]
    sha256 = "a2dea74b663e4a28c6290d91b985d85787ef486e3c64ca73c2c3bc7998a6a163"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.i686-w64-mingw32-cxx11.tar.gz"
[[libosrmc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7a929a6d66877a9abcf12869782f27cf2dd69a98"
os = "windows"

    [[libosrmc.download]]
    sha256 = "3b93e98527b9ac226fbdcf50100f2e0484d743da410843bd47fa4675bb9f70f0"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
[[libosrmc]]
arch = "aarch64"
git-tree-sha1 = "34ee5d00a3025b2f76e0aedb83bac6bd8ce15212"
os = "macos"

    [[libosrmc.download]]
    sha256 = "21a0094fc6975ce3c8c60238b0e8e702e45d82ca05070a8b84b9cf2a964d4bf3"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.aarch64-apple-darwin.tar.gz"
[[libosrmc]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6b25fb80fcb1c31fc2ab1a69345d5e8b3068d33e"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "56328da469fc0417605d4d6618abf49b9b3d292a52af7532d86ef4e6c9caf1d8"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[libosrmc]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f4d462d6fa74b2d10007dbbdfa8d0990e32411cb"
libc = "musl"
os = "linux"

    [[libosrmc.download]]
    sha256 = "c455a6835f767ffc69a5c5d98ed2ee2f5984d00c62514044155eac494e1cd9c2"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.aarch64-linux-musl-cxx11.tar.gz"
[[libosrmc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2133c8e6522383581bd67ec4681859edc1e751a0"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "965da800aaa3950315711485fd1444c04a402ff84b6e50e1f3ddca63af68f8b9"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[libosrmc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "74974d2a1ed2cd3834e747e18596248b3c0aed13"
libc = "musl"
os = "linux"

    [[libosrmc.download]]
    sha256 = "7b142a0dc0bca554c7972a4ae8bf5ec5b4a96571572caaa112505438900cf179"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[libosrmc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "05731633bb89eea5481acbb462b4de88f3259534"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "926052cab36439f0335d97c2cac0cf0cced517cae05cee2e7bbc2a6f9a20728e"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libosrmc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c5ab966ab982a863975a14aa9df1e2bd264cbc6e"
libc = "musl"
os = "linux"

    [[libosrmc.download]]
    sha256 = "aaab4f912a810bf0b6304f253e2b33499981cd8442e70d849cd9d9ab4d351056"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libosrmc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "900baa2e2dac842036ac1525d2654fea46d3e1ca"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "a5e9efbbb96f1b7317ed65a9d73888f86306a032dcb9cd32b08ae947474da589"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.i686-linux-gnu-cxx11.tar.gz"
[[libosrmc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "38a4da4d0ec60f32ebc7381b96982dddc1719d6b"
libc = "musl"
os = "linux"

    [[libosrmc.download]]
    sha256 = "9da1c333369199bba3b6d6159c3174aa6bbe39e21611dee371e0a1f454ede823"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.i686-linux-musl-cxx11.tar.gz"
[[libosrmc]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "89f2859fe9819122721714a82ef37721755fe06d"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "354ca9c3d82592cf0782b8e731516720443a136223f9fb32a61a3ce7b42665fb"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libosrmc]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c431fea68a8fa45efc542e30d314f17515f9144c"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "a61903e3d5af339539460161be494bd02fd7c66785ac3a45a741a65f75c41721"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.riscv64-linux-gnu-cxx11.tar.gz"
[[libosrmc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "29c1491400b9607db5e15bc73119d4a4ea56e07f"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "df5463329cf1cd7fe562e6bbe0f95f378c811981663f36a1b92ff28c890dd535"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[libosrmc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bb435b5a3e8af8d80fd1fe34e13347af8a9a8e93"
libc = "musl"
os = "linux"

    [[libosrmc.download]]
    sha256 = "6ae7d7694def721c152aa6b5726879a637c202f87ff35a2bddeeef89fbdca002"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.x86_64-linux-musl-cxx11.tar.gz"
