[[libosrmc]]
arch = "x86_64"
git-tree-sha1 = "417ae481304346bc85aa1e1ea6959f9dce053f5b"
os = "windows"

    [[libosrmc.download]]
    sha256 = "ef3864b2221fc90229dfb47c3f8a4d72b5de1d320d53f518bd891ecb626087d6"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
    [[libosrmc.download]]
    sha256 = "307ba7e01a1ccefa996a080012b4b8f147d3ef28ecd196cf34e8f0d8ec6562c7"
[[libosrmc]]
arch = "x86_64"
git-tree-sha1 = "f21cc23a333f5a80890fbc6e8edd60af073e810f"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "f96226e2b4f2f16d0e3fb051c0be6d2fbbc3bf907bb2eb17d44b2aa21eeee12c"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[libosrmc]]
arch = "aarch64"
git-tree-sha1 = "cec02f6f1656d43cebd3e46373b75bb1df225acf"
os = "macos"
os_version = "20.0.0"

    [[libosrmc.download]]
    sha256 = "8de5bc21fae3a81c00b307dae188baea9ab9d4124bcd850bbf2ef1c8cf39a9a1"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.aarch64-apple-darwin.tar.gz"
[[libosrmc]]
arch = "aarch64"
git-tree-sha1 = "1a36d3c4430182c9c44c4de74327acf8ba4ee9a5"
os = "macos"

    [[libosrmc.download]]
    sha256 = "c6e2856a7e99ad581bedf67e2527b3867f12841a073726831924a15a9e005b51"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.aarch64-apple-darwin.tar.gz"
[[libosrmc]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f7d6b9526e8b3f08047eba668f0403a6a8633ac4"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "c6166f7c726c4386bc6b8abdda0984d567208d50acd29a9a6e7696f455e8bdc4"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[libosrmc]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d9e68baa330d401736c45499031dda3b6b8a6b76"
libc = "musl"
os = "linux"

    [[libosrmc.download]]
    sha256 = "a35d28c982657a6c16d69a0715350d495fa9ea8b73a5c4e2940b39a0674b3f8b"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.aarch64-linux-musl-cxx11.tar.gz"
[[libosrmc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f462c7a2f6317bfb4aa87b614400d2fcd423e0cd"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "2eff3f175079e3335ece85d11ee74d9f39a351fdf40de03729f02d55f5f8c060"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[libosrmc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "db5ca6f13a4cfcf74277636e123d214bb3d9bdc9"
libc = "musl"
os = "linux"

    [[libosrmc.download]]
    sha256 = "c7ae2dfc1989121ffe2c227740f7b7749585d6bcf5a23711de26f568c877a192"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[libosrmc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a51af17691830be10a4e006e12fa7b5ba6030245"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "1bd94f25edf41465e08f03ce911f79947e6a9a97188b591c96673a1429189f88"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libosrmc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "885523d6106883ccc76c072a53c47f13e91576ef"
libc = "musl"
os = "linux"

    [[libosrmc.download]]
    sha256 = "3b2b7bc4855fb4e6c31618d50ab7aeca490054a88e09a976e781e7770c6741c5"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libosrmc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ab3ab1537afde1c049dd4c4ebad9a38018b21a29"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "84be545d6019c3fe40745fd7025486da2d1b8e6aa00e8416516e58428c040a6c"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.i686-linux-gnu-cxx11.tar.gz"
[[libosrmc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ed55b0058c3e809f05a937fb75f341fdac3aa49c"
libc = "musl"
os = "linux"

    [[libosrmc.download]]
    sha256 = "f7ab3db6fef605a1e7f204af0fd501b64994ff5d1c56811de48500a53cecab74"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.i686-linux-musl-cxx11.tar.gz"
[[libosrmc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5e0fa0f92ef4f30de250d0c0b1dce3f17aea4914"
os = "windows"

    [[libosrmc.download]]
    sha256 = "4852381de3c56d2258cb360e9d42d3ae6e7ba39c4ab2d67ef704da3fbb6f3dbb"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.i686-w64-mingw32-cxx11.tar.gz"
[[libosrmc]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7287fb468c8b740735749cf8d7fce3661e8a9ba9"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "4a52849ca3608e74f2bd766a4bec602914d9c072722cd6ded0729bd127dc56d5"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libosrmc]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "01da924c140b5a14a81e7ef1520098575d707b83"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "bb965ef119801c35e02fbfd415778341568bf1bad42444533f1b96011a41a8aa"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.riscv64-linux-gnu-cxx11.tar.gz"
[[libosrmc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "aa8c1fde3404ca72c1021e8dd48f3f53d079d424"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "b028e09983870534808dd6e2b5a0d68cb5cb935b1a9d5d99b581a7d85e10e1e0"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[libosrmc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0ee9ce4d26278deef9ed6ca505e92bf29e5c4da5"
libc = "musl"
os = "linux"

    [[libosrmc.download]]
    sha256 = "dfc0e96bf13dd102fba8d2f69c77dea94cb313c6d2e2c3c7aeed00d9e9b37de9"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.x86_64-linux-musl-cxx11.tar.gz"
[[libosrmc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9dbb100dc9f506d33b14317b6dffa15f24935781"
os = "windows"

    [[libosrmc.download]]
    sha256 = "f70ca76919e14ffce481e4d7bfeb8422e64b3ee23e07762adaf8969f973e2eec"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
