[[libosrmc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c6a1e9ffd41d4a71910362b68db60272361b59a6"
os = "windows"

    [[libosrmc.download]]
    sha256 = "a2dea74b663e4a28c6290d91b985d85787ef486e3c64ca73c2c3bc7998a6a163"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.i686-w64-mingw32-cxx11.tar.gz"
[[libosrmc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7a929a6d66877a9abcf12869782f27cf2dd69a98"
os = "windows"

    [[libosrmc.download]]
    sha256 = "3b93e98527b9ac226fbdcf50100f2e0484d743da410843bd47fa4675bb9f70f0"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
[[libosrmc]]
arch = "aarch64"
git-tree-sha1 = "ddaf0e3875b0d30003b9b46ef4d016b3a926ac4f"
os = "macos"

    [[libosrmc.download]]
    sha256 = "0b5361ab5ca91e8f26ae5e091c4f5f99409a1803aa3227fd1403074e364da0f8"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.aarch64-apple-darwin.tar.gz"
[[libosrmc]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "145b2dd4c5671ba2d7422540ee436749d7822fc7"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "7ebc39a042577b5781b2ba7c8f90b724bd0ff0f98d6ca1eb81ddc67d11c8ebc1"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[libosrmc]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c9c565d71c91f7d4511871a7d96769a0fe6dca97"
libc = "musl"
os = "linux"

    [[libosrmc.download]]
    sha256 = "3df3e33b39a0e37ba332bba586a8246e8e6bcefda2c39b4bdd413cf59b65f72b"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.aarch64-linux-musl-cxx11.tar.gz"
[[libosrmc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0c8a6a064da739764f7ee777ffcacec18a880100"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "86621f1782491ebcd1627f44ddfb43b918d9e8e1eb81f0b988925a150b3e6a2c"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[libosrmc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7b07d1091fd921fc75ae27be1cdfc17680219986"
libc = "musl"
os = "linux"

    [[libosrmc.download]]
    sha256 = "d192320c2de2456ce834b179907dc15035db5652a04c31537d96c6478d597901"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[libosrmc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "36ca1721c21d34038bc0f262bcc803a26b2f625e"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "3ea3b60a9d52fce08ba6b447644dd932b3f4b72c9114d511bde08b914fe40368"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libosrmc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0e707ae9957a8204824a3d126cb43d700fd66e91"
libc = "musl"
os = "linux"

    [[libosrmc.download]]
    sha256 = "b684841cb157d6b2ce6f244cca76f28d82b85805f71e917cba2dc0a15ade76ff"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libosrmc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "28e63b88c0f27e79d5640cd9dadf1d6e62fe098f"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "9ef20554cc14d5f449bbfd6c3e6c210fd5f4e9ea9f62f15763ea7df6adb3e814"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.i686-linux-gnu-cxx11.tar.gz"
[[libosrmc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d11709bd6c816ec432478945d487aab2bb561be6"
libc = "musl"
os = "linux"

    [[libosrmc.download]]
    sha256 = "e3d1ad014ccd9617ece2aec960686ac0300c2f62e474e63251bbefca40c0938b"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.i686-linux-musl-cxx11.tar.gz"
[[libosrmc]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8b1f3366340a9508d9b6e39fab01fedb78e7ee2a"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "fc4b32d44f11e6864054a44c4431fdc561e87f5e1c24044f776f2144ea87e40b"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libosrmc]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d8213bb36e854260397c0e7db1f8a9c8a630640c"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "5a4f4d2abb274b3f052fdba71c096c3df3e9488526ec759a5d31b3c4bf5bc406"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.riscv64-linux-gnu-cxx11.tar.gz"
[[libosrmc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4ce9c4311647d1577dc2ef54bb3b26d6436a6530"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "2f7a02bad4a7c6b91cdd3d33d1c2a69f5a17ec1803cb0658208a0284a6bf84ae"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[libosrmc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "776d23003e11597edcba4a40fabadf1d65d171fa"
libc = "musl"
os = "linux"

    [[libosrmc.download]]
    sha256 = "9e6b509ee40f61cd7d8bf02f29d9dff8cf87953a78fc20e758e4d62668659688"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.x86_64-linux-musl-cxx11.tar.gz"
