[[libosrmc]]
arch = "x86_64"
git-tree-sha1 = "417ae481304346bc85aa1e1ea6959f9dce053f5b"
os = "windows"

    [[libosrmc.download]]
    sha256 = "ef3864b2221fc90229dfb47c3f8a4d72b5de1d320d53f518bd891ecb626087d6"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.x86_64-w64-mingw32.tar.gz"
[[libosrmc]]
arch = "x86_64"
git-tree-sha1 = "a5c0fa788f3e9a360b446da8644023e8b52788c7"
os = "macos"

    [[libosrmc.download]]
    sha256 = "307ba7e01a1ccefa996a080012b4b8f147d3ef28ecd196cf34e8f0d8ec6562c7"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.x86_64-apple-darwin.tar.gz"
[[libosrmc]]
arch = "x86_64"
git-tree-sha1 = "f21cc23a333f5a80890fbc6e8edd60af073e810f"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "f96226e2b4f2f16d0e3fb051c0be6d2fbbc3bf907bb2eb17d44b2aa21eeee12c"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.x86_64-linux-gnu.tar.gz"
[[libosrmc]]
arch = "aarch64"
git-tree-sha1 = "cec02f6f1656d43cebd3e46373b75bb1df225acf"
os = "macos"
os_version = "20.0.0"

    [[libosrmc.download]]
    sha256 = "8de5bc21fae3a81c00b307dae188baea9ab9d4124bcd850bbf2ef1c8cf39a9a1"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.aarch64-apple-darwin20.tar.gz"
[[libosrmc]]
arch = "aarch64"
git-tree-sha1 = "cec02f6f1656d43cebd3e46373b75bb1df225acf"
os = "macos"

    [[libosrmc.download]]
    sha256 = "8de5bc21fae3a81c00b307dae188baea9ab9d4124bcd850bbf2ef1c8cf39a9a1"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.aarch64-apple-darwin.tar.gz"
[[libosrmc]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b650e65d947563694c1ca1c173f8e03132980e89"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "84b7e73e14d5d2a86d750d8658250843d67ad8e37af4ac8e2bf10103e924fc84"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[libosrmc]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "feb3b65ad70f00000202be52e61275c0a65b4a6e"
libc = "musl"
os = "linux"

    [[libosrmc.download]]
    sha256 = "2be8a375e2090843dfa32134a8b1b56dec5a52b0e6c1035dc1e70a48cd2d6ffe"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.aarch64-linux-musl-cxx11.tar.gz"
[[libosrmc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4747929fe36c0723a602e73e79a8ef3af3d29fcb"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "9864a07fadf8ebe357454a3d670f379db65e6270e6b1b97e656f348b209be992"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[libosrmc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ed07eaebd23bee746b98fc16f0b49cf0d09975c2"
libc = "musl"
os = "linux"

    [[libosrmc.download]]
    sha256 = "a5d425f531dd687942728ecdf4234119ba11e1deb900c2018caf5cb3db91c3e2"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[libosrmc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0157873bf9359f7523273c644097b58615e0b699"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "bcce25bd3cc76b170c4bd79a022655254f18d7bab8de336918eb0b405f1b47c2"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libosrmc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0d87bddddf080112ca87f28ae1177a5e68889b74"
libc = "musl"
os = "linux"

    [[libosrmc.download]]
    sha256 = "e09e9c64723e2087802149214128e70361a88dfd6d277fff94ce77fdb99b5e26"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libosrmc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "406182694124fb1fa5c8a5de48bceac75276675e"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "da9e7bf9cecdba49bd6e581e604c015e65d1c190bf32caeda6ac44d3b9c6249c"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.i686-linux-gnu-cxx11.tar.gz"
[[libosrmc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4aadf669c93566272ea5efa71f6d0af97dd65ffa"
libc = "musl"
os = "linux"

    [[libosrmc.download]]
    sha256 = "5354d580b83193083b6def0dfc55206f41740f98bc714fa913287e7a5afcdcb7"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.i686-linux-musl-cxx11.tar.gz"
[[libosrmc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8dcdc965e817ea7c814874b87b9b9316fb07411b"
os = "windows"

    [[libosrmc.download]]
    sha256 = "334096cf1abfeb8f4e25806c54d0203c430edebe31a0916b5e17914fd5bd9bef"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.i686-w64-mingw32-cxx11.tar.gz"
[[libosrmc]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e87efe249e08eafc46bc635fc2a88a000fcd6562"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "8bbd47229d853ff3e29e79df035a12a36c81dd13f6072b42e804b91b69746859"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libosrmc]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "380e3eba434ccb2f3705f038524e5a05f1456db7"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "897632c3d1e6299faf9469037f281996a5b792e39287f6f3085283e58188a30b"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.riscv64-linux-gnu-cxx11.tar.gz"
[[libosrmc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f21cc23a333f5a80890fbc6e8edd60af073e810f"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "f96226e2b4f2f16d0e3fb051c0be6d2fbbc3bf907bb2eb17d44b2aa21eeee12c"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[libosrmc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "88ae026ceb168fdefc6fc777e343f42ce709d02d"
libc = "musl"
os = "linux"

    [[libosrmc.download]]
    sha256 = "6e1fabc971c654d9ff18ceaa0815ee5ee1c16c6fdb345973348adb3e7fdcf016"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.x86_64-linux-musl-cxx11.tar.gz"
[[libosrmc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c2ca502660c587410ee1d6918ac6457bf8bf5a40"
os = "windows"

    [[libosrmc.download]]
    sha256 = "b192308319469d98754dee01efda7b562f83dc24863b76fa2375adce3ebffe1c"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
