[[libosrmc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c6a1e9ffd41d4a71910362b68db60272361b59a6"
os = "windows"

    [[libosrmc.download]]
    sha256 = "a2dea74b663e4a28c6290d91b985d85787ef486e3c64ca73c2c3bc7998a6a163"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.i686-w64-mingw32-cxx11.tar.gz"
[[libosrmc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7a929a6d66877a9abcf12869782f27cf2dd69a98"
os = "windows"

    [[libosrmc.download]]
    sha256 = "3b93e98527b9ac226fbdcf50100f2e0484d743da410843bd47fa4675bb9f70f0"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
[[libosrmc]]
arch = "aarch64"
git-tree-sha1 = "2dd60e22b4f7e8ddf6631a4c698b22cf4f808f5f"
os = "macos"

    [[libosrmc.download]]
    sha256 = "c489afc9cff5eb5602d57cdbd92290abf93aab877814f0d3e96e3b7bfc05a18b"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.aarch64-apple-darwin.tar.gz"
[[libosrmc]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ab587a4c100863ffc9ea24770856e16a5b8ccdbe"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "c89d4290b6b15a14a65a38d35c8a7e06e58f100b042aea0774ae9436bed15458"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[libosrmc]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a78150c09dde23ceb4db268499d67ff8497c82ec"
libc = "musl"
os = "linux"

    [[libosrmc.download]]
    sha256 = "80dc3e21eae928a516ca43da92833f3edf50a7cd531056b34d8151050e9a1f92"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.aarch64-linux-musl-cxx11.tar.gz"
[[libosrmc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5b9111199263f829947032aada33a142ac2f1bd5"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "ee3eec671d3dc22b146ef3e1a5232faffe2ee60f8dca9a35382cb8166087e0da"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[libosrmc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5ce642b1d19f13766cf01c1028b37ef072f49a02"
libc = "musl"
os = "linux"

    [[libosrmc.download]]
    sha256 = "4e26758db1937d5780809860ba028e092a9a34997979afd0cd07733b8ec23343"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[libosrmc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7234119ff75973120be44cb601a25a27f5e05713"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "0b4e9083f617fc31204c11046b5fa80037e8d93baaf681099c0bcfa46675112b"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libosrmc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4522b9a4ed0dcba097940bb35e5ac4fc6c2484dd"
libc = "musl"
os = "linux"

    [[libosrmc.download]]
    sha256 = "7a94bba7748bf1e8b085067e6d6dc6ee3ea12f09630e7ba45a6a57c30c699305"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libosrmc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9e9693327c6b6ff0a505c27a1b9ecbda6b4a01f0"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "8551ad7d3d1cf553980999e134e83ee5c1a8b8096f8ada1ff78ee5311e6988cd"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.i686-linux-gnu-cxx11.tar.gz"
[[libosrmc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0fd7b0b14cd87c0105c9099b90bff08f05f37c5f"
libc = "musl"
os = "linux"

    [[libosrmc.download]]
    sha256 = "815330b1814ef98424ea54b4a8eabb9d76c23de82600f46d3e51c7e8482aae55"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.i686-linux-musl-cxx11.tar.gz"
[[libosrmc]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f5cc5648256c375ba411a513885e3a878bee7c8a"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "b7f827ec7dafad3ee6a4f820e59209bae9dcc22c457a868f1c1b7dd68b0f7dfd"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libosrmc]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c8941dc10d42bf1568156cb95e73a492400f6c4b"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "c71172e89e0ce11ddaacc63f8e13cc6d40ee6a316cd5548987579928e6cbf3c0"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.riscv64-linux-gnu-cxx11.tar.gz"
[[libosrmc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5bf388d2e969dfb11a9de84b3875b549ffbb8d30"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "fec4f8d9449cb98fcaa0095d9cb35c9179718b841129a57f9e59328346568fea"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[libosrmc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "01256b38eb51dc6af8226adf1147ee73f8a2e3c5"
libc = "musl"
os = "linux"

    [[libosrmc.download]]
    sha256 = "5d9287e3c18ebe7819d9f17fae8ecde8523b9b9ce0059e575977285363d4c65e"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.x86_64-linux-musl-cxx11.tar.gz"
