[[libosrmc]]
arch = "x86_64"
git-tree-sha1 = "417ae481304346bc85aa1e1ea6959f9dce053f5b"
os = "windows"

    [[libosrmc.download]]
    sha256 = "ef3864b2221fc90229dfb47c3f8a4d72b5de1d320d53f518bd891ecb626087d6"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
    [[libosrmc.download]]
    sha256 = "307ba7e01a1ccefa996a080012b4b8f147d3ef28ecd196cf34e8f0d8ec6562c7"
[[libosrmc]]
arch = "x86_64"
git-tree-sha1 = "f21cc23a333f5a80890fbc6e8edd60af073e810f"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "f96226e2b4f2f16d0e3fb051c0be6d2fbbc3bf907bb2eb17d44b2aa21eeee12c"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[libosrmc]]
arch = "aarch64"
git-tree-sha1 = "cec02f6f1656d43cebd3e46373b75bb1df225acf"
os = "macos"
os_version = "20.0.0"

    [[libosrmc.download]]
    sha256 = "8de5bc21fae3a81c00b307dae188baea9ab9d4124bcd850bbf2ef1c8cf39a9a1"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.aarch64-apple-darwin.tar.gz"
[[libosrmc]]
arch = "aarch64"
git-tree-sha1 = "2c6bd484ebd4dba70969e6b490b0ffb8e0cab9bc"
os = "macos"

    [[libosrmc.download]]
    sha256 = "90592674f146dd8a3c4947ba38c037a5e6de73fc207a3b1696b5d033cd293b42"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.aarch64-apple-darwin.tar.gz"
[[libosrmc]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "34456229b086b5bb554325d44747671bdadabc63"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "c6c75997243b0073969b2ccd860460e52bc2f6d2ee8c66a6a26c373a1ef3f125"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[libosrmc]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "131b16bbddac6f9b95b6274993c68f5454f0b012"
libc = "musl"
os = "linux"

    [[libosrmc.download]]
    sha256 = "bd42ea5e166c8829682f29d2d4afd746ce211767978a3a5e8c6a5ff5f4c3166d"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.aarch64-linux-musl-cxx11.tar.gz"
[[libosrmc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "165649765889bb40029a00c1f2307293ce16abb1"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "2ec29c31d871e7e23d2eb7b6153dea3a482b1600d5194c184acac831dc809947"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[libosrmc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8f0f1da7ffa11b11d969b49f497024c8f02131d3"
libc = "musl"
os = "linux"

    [[libosrmc.download]]
    sha256 = "f44ac2df7673297ff9722466180d6e07b119d23573ac47c81f10b185c72b4b6f"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[libosrmc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "776f95490a9064108221b0d243e1ea0e18a8a26b"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "c813c402a4bf022cbd7b3f4a3f61c0159a8ffd817c46bb18d62451064efcefaa"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libosrmc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "371690e8dfc8d244796af157ae3e28833d4cc297"
libc = "musl"
os = "linux"

    [[libosrmc.download]]
    sha256 = "c4e95be774152815f22397e18543bcdb4d5b7f6e65ac33a69f7a2aff0ecdcc42"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libosrmc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "30e064e02bf9c38494cea42d93eb38d5a57472d3"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "fa2c8842bb793d693b7dcb8ce83dc9ec6212caad02f1eaa4da8cb678ab278587"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.i686-linux-gnu-cxx11.tar.gz"
[[libosrmc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "89f0d912296bb6cbf6a750f1bbc48e8dce509f27"
libc = "musl"
os = "linux"

    [[libosrmc.download]]
    sha256 = "0c0a187d1eab697738e2ce520302d8861776e0558ee8c1927a1f0e426b70f4dc"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.i686-linux-musl-cxx11.tar.gz"
[[libosrmc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "37bceaffe67b474985e4e4c7036babf8732612e0"
os = "windows"

    [[libosrmc.download]]
    sha256 = "18115123862c237eb92471634cd530ae42eb770693c5a9f8fb9e52c78ee20ab0"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.i686-w64-mingw32-cxx11.tar.gz"
[[libosrmc]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6b3d6f62bbecf36054e0265fe6b96f2d509d1348"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "7167ed698ccb58cc036f5fd964d16b3225a9ff9049725d8671be3cee42bef262"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libosrmc]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "050fd7b233725cdcc270e565922790df2fe4d23b"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "69a3bf89c48eec4bac59caa6f1626a82a230f369bf86a8a913ea867582bdf9ae"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.riscv64-linux-gnu-cxx11.tar.gz"
[[libosrmc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "72a41d09db1b5dd389ee153e7a12f0b706d72731"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "649161722259f8b0c19158ccfd4dabf0a942429099f71df9478ea4915b54838a"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[libosrmc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "438d77158f0392c2ffd89d7819c95184eb192b31"
libc = "musl"
os = "linux"

    [[libosrmc.download]]
    sha256 = "ccbfdc8c23150357eee2232f5b39ed5e5973868540b6fe186be79b09c4bd0a0f"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.x86_64-linux-musl-cxx11.tar.gz"
[[libosrmc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1d7ce29a795a5e011828cd7627ae7bdc18a1cc3c"
os = "windows"

    [[libosrmc.download]]
    sha256 = "dd7642be6ff3b99a0f83861406d48e941b84188daf0c46d2b789ceeee8f43f30"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
