[[libosrmc]]
arch = "x86_64"
git-tree-sha1 = "417ae481304346bc85aa1e1ea6959f9dce053f5b"
os = "windows"

    [[libosrmc.download]]
    sha256 = "ef3864b2221fc90229dfb47c3f8a4d72b5de1d320d53f518bd891ecb626087d6"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
    [[libosrmc.download]]
    sha256 = "307ba7e01a1ccefa996a080012b4b8f147d3ef28ecd196cf34e8f0d8ec6562c7"
[[libosrmc]]
arch = "x86_64"
git-tree-sha1 = "f21cc23a333f5a80890fbc6e8edd60af073e810f"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "f96226e2b4f2f16d0e3fb051c0be6d2fbbc3bf907bb2eb17d44b2aa21eeee12c"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[libosrmc]]
arch = "aarch64"
git-tree-sha1 = "cec02f6f1656d43cebd3e46373b75bb1df225acf"
os = "macos"
os_version = "20.0.0"

    [[libosrmc.download]]
    sha256 = "8de5bc21fae3a81c00b307dae188baea9ab9d4124bcd850bbf2ef1c8cf39a9a1"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.aarch64-apple-darwin.tar.gz"
[[libosrmc]]
arch = "aarch64"
git-tree-sha1 = "04ae60024e0e06c265d1550a156db3cde110477b"
os = "macos"

    [[libosrmc.download]]
    sha256 = "ed01fb78a3129eb9e2eef19fff3c7fc2076c1ef812310c20df0dc9cbe5800269"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.aarch64-apple-darwin.tar.gz"
[[libosrmc]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6dda82f49e3f8125fcb765f1d3f549d8a1fbd63a"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "428ae2569c6821271f111325693ffebac51480e8b231e920400289692bf4ec77"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[libosrmc]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7d2298d2a1cd2f19a94d269def4e4792bcc93a03"
libc = "musl"
os = "linux"

    [[libosrmc.download]]
    sha256 = "b3fac631316af5085ecd73f343210f3a0ed3981264b0f8374a1eb784f505b932"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.aarch64-linux-musl-cxx11.tar.gz"
[[libosrmc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b0cbfc41d564a137d74cc61ac40f09aa68e6fdd3"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "24bdbef7ad54deb3c05dfc2e847e2e5eb12d0d4bb5f37667f3ec672662dad5f0"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[libosrmc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c6e0014f2cabfd85df5225e712d16dcc9a011ca9"
libc = "musl"
os = "linux"

    [[libosrmc.download]]
    sha256 = "a27443a6c2be9c2384d25582d550836a1ef865c65781070edf250f4aa1cd21e0"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[libosrmc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9b551ac14a0de16ff587967bc93501cef31240c4"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "a169523679afe132c5f6a59863b7d97e89284c1068b46c3896fb31703d771ad7"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libosrmc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "36c44c22ae84ebf8c76ee7738f385eec89845bf5"
libc = "musl"
os = "linux"

    [[libosrmc.download]]
    sha256 = "fcec6030bf7e34ca622ca415ac6249ef20f429d5e6d9cf9e2b77eb51ba88058d"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libosrmc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "886cab33e903b021396f9682d4875622127def5b"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "7fb109ef5c2d4fc4a1a111d6acae6ebf823db4ed1e0cc146c2b8ae03df5d7838"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.i686-linux-gnu-cxx11.tar.gz"
[[libosrmc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d89604bb364eb14dd6a36fb70a7eefa3234fffb7"
libc = "musl"
os = "linux"

    [[libosrmc.download]]
    sha256 = "5ca79a431f595d6caf9004bf8c1b23e6eba76a5d96ce405faea1409416be19bc"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.i686-linux-musl-cxx11.tar.gz"
[[libosrmc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bcb5aae8b02f84e4235f0201342dbdffaa92d003"
os = "windows"

    [[libosrmc.download]]
    sha256 = "21f0e6a720bfb9bf6ebb3052fc20b35e3d91d3e37d3daf9f8d85b7f68c324ea9"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.i686-w64-mingw32-cxx11.tar.gz"
[[libosrmc]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a5e23730375e1986adae1a8b91c812a1d58b65dd"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "98a425291898f0910a00da5eaee77f27122949a448dfb859d63c034d2602cfac"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libosrmc]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9311c282789a5a7c579bd420093d40a73d081c34"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "fd67327f5d09d686d3b50e8e009a428d2e0272bd8ecf17036432a0a538312e6f"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.riscv64-linux-gnu-cxx11.tar.gz"
[[libosrmc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "88b0aa3cd17659bde037af9afe125f1b08cc2860"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "50878720628c699db2f9edc3ead0ecce47f2ae5d3ae9bee99421c3fc30665ffc"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[libosrmc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c343a435edd9b4588faf38c7a2d16069072fac26"
libc = "musl"
os = "linux"

    [[libosrmc.download]]
    sha256 = "27aad2baad4a05b637aaa743a91aea0ea01c973f9e4d500d8814d4521ad6f7f9"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.x86_64-linux-musl-cxx11.tar.gz"
[[libosrmc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "430f0e2ad1255ae538e94c7ba1fa469ba31cde4d"
os = "windows"

    [[libosrmc.download]]
    sha256 = "f87e723f4b10c37a5b31c55aaa54cb443033a0481f1a4881d0620a320e70c140"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
