[[libosrmc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c6a1e9ffd41d4a71910362b68db60272361b59a6"
os = "windows"

    [[libosrmc.download]]
    sha256 = "a2dea74b663e4a28c6290d91b985d85787ef486e3c64ca73c2c3bc7998a6a163"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.i686-w64-mingw32-cxx11.tar.gz"
[[libosrmc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7a929a6d66877a9abcf12869782f27cf2dd69a98"
os = "windows"

    [[libosrmc.download]]
    sha256 = "3b93e98527b9ac226fbdcf50100f2e0484d743da410843bd47fa4675bb9f70f0"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
[[libosrmc]]
arch = "aarch64"
git-tree-sha1 = "488a4dd23d1dcac198df6f1e1f3f0a894d32f968"
os = "macos"

    [[libosrmc.download]]
    sha256 = "38b87e2ddc63963dc2fb4875fe7b89cd93b1ae6804596f1fe2463a20a85aba6f"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.aarch64-apple-darwin.tar.gz"
[[libosrmc]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "556b59891e53c0f9a5a1dd05af9e14bbd39a0e51"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "4d71365a0ac4e4ee8f75298e960853cea11852350db86c20fd1dcc4f5d3a2baa"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[libosrmc]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5203bbc954a73ba92dc610ca1d69d9a47fd97d99"
libc = "musl"
os = "linux"

    [[libosrmc.download]]
    sha256 = "cb0e03c86611ca27239bb4cf85b401a08121270d2eda68b8d88f30c2ca089df4"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.aarch64-linux-musl-cxx11.tar.gz"
[[libosrmc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "18bc082344c0f00d41baed0e53e34c73ccfac3fa"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "22cec8d9dbca8eb4466a607e5094d109a28ae44c9c100eabd7671fdde7bed52a"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[libosrmc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "aa663b3a743b62547b5a8d481b58d3dd46c724e1"
libc = "musl"
os = "linux"

    [[libosrmc.download]]
    sha256 = "73f49c1b1c4dd2d6c6a0033cb35a8f7aaec145f2d0a654fdf1f6ebad693aacf4"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[libosrmc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8800710124f7bf57d3e6c08fe7071af6d8a9917b"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "336f05c3d774590bce658b796df85dfe10dce11eaddc0a4d3c95389ea0cfbb12"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libosrmc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d48e49a5f8379833efcd55e5751199af19d6b6b1"
libc = "musl"
os = "linux"

    [[libosrmc.download]]
    sha256 = "c40336a806fecb88e3e5ea872f1f9ed9aa6142fe3cdf64f201a639de4cf81d56"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libosrmc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0552b4c46f79fb85851adabb48cce5508ce711e7"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "549b13f3e37e620e328631bc88ded1afa100046c6fa403b78884a19ab2129396"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.i686-linux-gnu-cxx11.tar.gz"
[[libosrmc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f81a425defd1330f9ff2fe5ed9a07d01080e8941"
libc = "musl"
os = "linux"

    [[libosrmc.download]]
    sha256 = "a74c61f7d3b663f3a77bf469b31fd1f0e8bb02e159d4b85a2b9179e4b9deb007"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.i686-linux-musl-cxx11.tar.gz"
[[libosrmc]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cf03366a68f45c533488e003eceaa011212fc00f"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "bfa8fd1e4acfc0db88d8eed9ec688f5d030e89fcb71fd63edba0b312ef9aca52"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libosrmc]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3e7e53ee690d175ee05a04fac13f72119c257a4e"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "13ea2353730a3a04a188f1255fa9871ad35fff086a8993b659dcc01105652bd2"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.riscv64-linux-gnu-cxx11.tar.gz"
[[libosrmc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fbbe63f3ec78caadc13dc3ffee3c12899ab702d5"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "9ad408759fd9a4beb6dc6163aca8a2a79b456ba88fc443f26f9aa7df8c16b3c1"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[libosrmc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "928ebb925d85f8e72ff8c39935131d388bdc36af"
libc = "musl"
os = "linux"

    [[libosrmc.download]]
    sha256 = "6bf48703a33ca5f62673d33bd31e52122f4d042ec13658a2c74bf9842e1fbb4e"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.x86_64-linux-musl-cxx11.tar.gz"
