[[libosrmc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c6a1e9ffd41d4a71910362b68db60272361b59a6"
os = "windows"

    [[libosrmc.download]]
    sha256 = "a2dea74b663e4a28c6290d91b985d85787ef486e3c64ca73c2c3bc7998a6a163"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.i686-w64-mingw32-cxx11.tar.gz"
[[libosrmc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7a929a6d66877a9abcf12869782f27cf2dd69a98"
os = "windows"

    [[libosrmc.download]]
    sha256 = "3b93e98527b9ac226fbdcf50100f2e0484d743da410843bd47fa4675bb9f70f0"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
[[libosrmc]]
arch = "aarch64"
git-tree-sha1 = "49ba0ae8435d3984b2d6e41fa0811891fc7be0d0"
os = "macos"

    [[libosrmc.download]]
    sha256 = "3f8eb1763328fd6ddeed03d8513e09b78ab26f5b9fdbde84951701e8643d15df"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.aarch64-apple-darwin.tar.gz"
[[libosrmc]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6b2550094bba15fc5ff33787a235ab1dac808b18"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "110bb0a931df385442b6f35138fd654b3c53cbb5820febff851a256111491d80"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[libosrmc]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "88a2a86e8e2bd1804233da38543119011cd636a0"
libc = "musl"
os = "linux"

    [[libosrmc.download]]
    sha256 = "c652e97f0fabeb02bb9ead0d4dca702660b22e679d6fa0926e4631700408170d"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.aarch64-linux-musl-cxx11.tar.gz"
[[libosrmc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5c066efffba7b9472f9281d2c8fb9cda14173c75"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "f87df0de7530a2930c58e68c0b7162a455e99476582e75daafaab8f4073a42c2"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[libosrmc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1b92c8f001aaafa1f0b34c54bff30d3d65ab8aed"
libc = "musl"
os = "linux"

    [[libosrmc.download]]
    sha256 = "d7e95398da84801f05fe839f54b1e599149ffbbcc2ea4d219ed3fca626eccdf2"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[libosrmc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d2dea3b13824a096e5063d6019d6343a9e8c1c73"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "6b9f0432977fdab0979a530ad252ad48149190b7ce87d52159b3af94888ea7a6"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libosrmc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0491832730d18cfe763d935439a7af399c78c0ee"
libc = "musl"
os = "linux"

    [[libosrmc.download]]
    sha256 = "3a0e3b2f72ea962ff09469023faa6ac13f3669104a0fe78efa363261404aff9c"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libosrmc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8b1d0cb1998cf69c51d433f3e493912ff3e6d889"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "2e0476c86b62afd471b84b5fbcad2cb8373211dda58bac7944bce12cb8405922"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.i686-linux-gnu-cxx11.tar.gz"
[[libosrmc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ca9ecc30d2bd50a30f554019057e5d10ba7e58f4"
libc = "musl"
os = "linux"

    [[libosrmc.download]]
    sha256 = "4674331e852b7f6914a1325254d16a767b90d0958240bc89e081122e45dafa24"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.i686-linux-musl-cxx11.tar.gz"
[[libosrmc]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "11a985200fbcff3b2d75c9148c187f41320fdaf3"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "b05ec297748702e9b1f2e6cfa95d8046a11af2cdfdf9b9d552688e9aa7939151"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libosrmc]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4a221a4ac20b702dada689f6ad73713594d29ae4"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "ba1974f5e764d44c205f301e76aef265af57b4eda0fade9915e871bb3a4aadf8"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.riscv64-linux-gnu-cxx11.tar.gz"
[[libosrmc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "04adb26ddde8de3b4e580a216edc32d931ab9348"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "4520551386a047742e3b768528baa100e3821215a519b73c2b7ecf24fa593edf"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[libosrmc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c256888cda4a93318630dece7d79a0744b015278"
libc = "musl"
os = "linux"

    [[libosrmc.download]]
    sha256 = "5155c475ba4bca23cc92fe49fb32d45bdf3eef7dfb0c6d8333d5bd0c2563d61a"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.x86_64-linux-musl-cxx11.tar.gz"
