[[libosrmc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c6a1e9ffd41d4a71910362b68db60272361b59a6"
os = "windows"

    [[libosrmc.download]]
    sha256 = "a2dea74b663e4a28c6290d91b985d85787ef486e3c64ca73c2c3bc7998a6a163"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.i686-w64-mingw32-cxx11.tar.gz"
[[libosrmc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7a929a6d66877a9abcf12869782f27cf2dd69a98"
os = "windows"

    [[libosrmc.download]]
    sha256 = "3b93e98527b9ac226fbdcf50100f2e0484d743da410843bd47fa4675bb9f70f0"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
[[libosrmc]]
arch = "aarch64"
git-tree-sha1 = "e5f3fb9fe94121f22fe898552cbee70bafca8dd3"
os = "macos"

    [[libosrmc.download]]
    sha256 = "5b8d6c4b8541ee62fddd0cca2acc9ff2ff5fce0b091f337e13817bc263105975"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.aarch64-apple-darwin.tar.gz"
[[libosrmc]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9a8afe40d6bef77e13df4666d130c7b83c6c7490"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "b0b5d119b5ad1f52d4eba69f94686d2b4bdda684f128a954df72ac223ac64a28"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[libosrmc]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "487a61192584407e103507738a175e7c8a1db429"
libc = "musl"
os = "linux"

    [[libosrmc.download]]
    sha256 = "ad5a549decd05b3cea427bd59785dd173d0abd286c4cf01ac9c7c7cbc8ad26ee"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.aarch64-linux-musl-cxx11.tar.gz"
[[libosrmc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "04ee10b50ac284a1f5bf47fd5ed6b3b776f8a621"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "9fa38a05f06902c6b9436ebfcda155e8ef745a0efd775129161f531bfd4996c2"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[libosrmc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5e689e3a0518f26f1cb03b48c9ea078053c918b2"
libc = "musl"
os = "linux"

    [[libosrmc.download]]
    sha256 = "434f7baec3eea7b5f4ad0692c0e5934ae4df40b5c49c47db4fb2d1abc3eb96b7"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[libosrmc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8c20429c29b0fdf1bb9f3572fafd14e74bb9d892"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "cc7e83a7a1630f45b4aba8045e437a2f52a9f9d84f64ab6705725d3523f3fb84"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libosrmc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8ccb4b11a24a75dc381e6d0a1238bf21f66d5104"
libc = "musl"
os = "linux"

    [[libosrmc.download]]
    sha256 = "5394f409ffc5e71c904659bdab7ffcb3b6964f33789e0c37d7b181561329861f"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libosrmc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a5840f83952dfa59585f09ff636488817eb7e628"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "3102cb25075841a2600ef09eb4704a34005b392fce5ccdefa9408a24a5611db2"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.i686-linux-gnu-cxx11.tar.gz"
[[libosrmc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8f9dc035942a1d08d098dcf12176eb7871f068df"
libc = "musl"
os = "linux"

    [[libosrmc.download]]
    sha256 = "fc82fa2a42e4ff76e75391a979d066633a6db28212ba88ad765ce96ffa6a8533"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.i686-linux-musl-cxx11.tar.gz"
[[libosrmc]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7bb067c0cbe7baa4bfdf5cc31a5c62b599aced10"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "939730bcf497b1b12df7328a2614a48514cbd28ff86c254246d824093cd78e8c"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libosrmc]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5dcad8cd49af7b55edf77f77ffb56a337f10f361"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "d9bde154d459cabdbec03541dd7ba8732453d7e75638826415002b3fe2259256"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.riscv64-linux-gnu-cxx11.tar.gz"
[[libosrmc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "69909a91239513a0c810d98c219edcf2f84b8ebc"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "0b652c7855ac091830ff6a748f3dd028e4a36b2466d4ca57800849adcf6d18f1"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[libosrmc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "df1a8c6f41ad1dc0615c086a4a7b4f8acf6ae528"
libc = "musl"
os = "linux"

    [[libosrmc.download]]
    sha256 = "5a2f825622bd294ba253012eb7f8509cd701cf8c4c10442ce4c2c1733718dbd2"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.x86_64-linux-musl-cxx11.tar.gz"
