[[libosrmc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c6a1e9ffd41d4a71910362b68db60272361b59a6"
os = "windows"

    [[libosrmc.download]]
    sha256 = "a2dea74b663e4a28c6290d91b985d85787ef486e3c64ca73c2c3bc7998a6a163"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.i686-w64-mingw32-cxx11.tar.gz"
[[libosrmc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7a929a6d66877a9abcf12869782f27cf2dd69a98"
os = "windows"

    [[libosrmc.download]]
    sha256 = "3b93e98527b9ac226fbdcf50100f2e0484d743da410843bd47fa4675bb9f70f0"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
[[libosrmc]]
arch = "aarch64"
git-tree-sha1 = "03a9a9e43702f0ebc6553ac80dbcb1642dbb2551"
os = "macos"

    [[libosrmc.download]]
    sha256 = "d75571afb0b679effa4862ee09f2aa64a365149a1274632c4b7f58b42423fc44"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.aarch64-apple-darwin.tar.gz"
[[libosrmc]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ac60f3692dc17d976884bd8adae5b1bc140a550d"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "a85f4541e4c789e88ecd74d86da02ee2660d08c54b6842946ff9dedfd5bdb67c"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[libosrmc]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4ce8244ab9ecbf4ff1870816a6d4372e0f37d319"
libc = "musl"
os = "linux"

    [[libosrmc.download]]
    sha256 = "1270db42c9c2470466892c6a80b4dfaba6f1f8f73a271c950e49340ff36753bc"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.aarch64-linux-musl-cxx11.tar.gz"
[[libosrmc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9844ae46cfd84c694d5c57e8e0a140609a5a1f17"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "a2718bfaff020add73ae1c64e9d9b4f489f684bbc71fc2dd0203a9ce559bf8b7"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[libosrmc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f634c43e6b6892752d5c3c44238d73d4422bc5b5"
libc = "musl"
os = "linux"

    [[libosrmc.download]]
    sha256 = "ed036bf251c260929b4a993dba3165202d9191b6eeaa70eb72556988b9561d81"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[libosrmc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "05d47628305a988f278ffc50395f74e72d122c45"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "885733cff0fa2449880232a436efeb7b0997227ab9171f1c7ca3476706dc9090"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libosrmc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "497dd164247e6dffd135bc363cb0eb90286e2d91"
libc = "musl"
os = "linux"

    [[libosrmc.download]]
    sha256 = "b0e2995ce4ae4ea036dd38f73a64d2cfd6cf7415e8813010773f72ba734888e0"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libosrmc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dbc2ff372505dade26da05baec71e100cb89cb61"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "0a9613e2f524c4e499ad285ac6da7bcd8ca2acaa494517e5c11d1a023d993152"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.i686-linux-gnu-cxx11.tar.gz"
[[libosrmc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b19d953de723ed38adfa6f07c2c2ef7d3dd2ea07"
libc = "musl"
os = "linux"

    [[libosrmc.download]]
    sha256 = "3be982caecb001d8e0d358a8424c0a74642efa57f587512918a60fbc74496018"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.i686-linux-musl-cxx11.tar.gz"
[[libosrmc]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "19292387c19b140ae714a4875a46679f7dd617ba"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "70e62994607473d02ff3f06bfa62fd71ec3cc906da33706f13f6978c59996e07"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libosrmc]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "adfa7ad5ff5accef879140c42035b76849136d1a"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "c49b052c47ec0f7353b80c414ff47594bc918eb6e304bae6dd83626ed5587b54"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.riscv64-linux-gnu-cxx11.tar.gz"
[[libosrmc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9d1b9c87e8667ff6a31d3538989d5e4e098fd659"
libc = "glibc"
os = "linux"

    [[libosrmc.download]]
    sha256 = "7cbc1a3e20092a4394d2fd0049231736010e973413554f4d50b2ed1f5bc9ce00"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[libosrmc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "657a8ffcdd61425e908b9c0a8c405919d1cc6d11"
libc = "musl"
os = "linux"

    [[libosrmc.download]]
    sha256 = "313b3d55115e74231867ec3dd4892136b12b0c46cd266048fd509dc35e007cf4"
    url = "https://github.com/jrklasen/libosrmc_jll.jl/releases/download/libosrmc-v6.0.0+0/libosrmc.v6.0.0.x86_64-linux-musl-cxx11.tar.gz"
