name = "libosrmc_jll"
uuid = "b012619c-76c7-5216-bb6b-491eaf671aba"
version = "6.0.0+0"

[deps]
JLLWrappers = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210"
CompilerSupportLibraries_jll = "e66e0078-7015-5450-92f7-15fbd957f2ae"
Bzip2_jll = "6e34b625-4abd-537c-b88f-471c36dfa7a0"
Zlib_jll = "83775a58-1f1d-513f-b197-d71354ab007a"
OSRM_jll = "a74304e1-5a13-544f-adb7-0572470cee19"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Expat_jll = "2e619515-83b5-522b-bb60-26c02a35a201"
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
boost_jll = "28df3c45-c428-5900-9ff8-a3135698ca75"

[compat]
JLLWrappers = "1.7.0"
julia = "1.10"
OSRM_jll = "6.0.0"
Libdl = "< 0.0.1, 1"
Expat_jll = "2.6.5"
Artifacts = "< 0.0.1, 1"
boost_jll = "=1.87.0"
